---
- name: Setup Minecraft Server and Run nmap
  hosts: minecraft
  become: yes
  tasks:
    - name: Update apt repository and install Docker
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Ensure Docker service is running and enabled on boot
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull Minecraft Docker image
      docker_image:
        name: itzg/minecraft-server
        source: pull

    - name: Create Minecraft server data directory
      file:
        path: /home/ubuntu/minecraft_server_data
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Run Minecraft Docker container
      docker_container:
        name: cs312_minecraft_server
        image: itzg/minecraft-server
        state: started
        ports:
          - "25565:25565"
        volumes:
          - /home/ubuntu/minecraft_server_data:/data
        env:
          EULA: "TRUE"

    - name: Run nmap to check Minecraft server port
      command: >
        nmap -sV -Pn -p T:25565 54.186.110.29
      register: nmap_output
      delegate_to: localhost

    - name: Output nmap results
      debug:
        var: nmap_output.stdout
